---
#
# Ansible managed
#
repository:
  description: Install and Configure NVIM on your Linux systems.
  homepage: https://buluma.github.io/
  topics: development, nvim, neovim, editor, ansible, molecule, playbook
